# Generated by Django 5.1.3 on 2025-04-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_compra',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Precio de compra'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('MATERIA_PRIMA', 'Materia_Prima'), ('ARTICULO', 'Articulo')], default='ARTICULO', max_length=20, verbose_name='Tipo de item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('gr', 'Gramo'), ('lt', 'Litro'), ('ml', 'Mililitro')], default='unidad', max_length=50),
        ),
    ]
