# Generated by Django 5.1.3 on 2025-04-06 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_detallecompra_precio_compra_alter_item_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_compra',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio en Gs.'),
        ),
    ]
