# Generated by Django 5.1.3 on 2025-04-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_categoriaproducto_alter_cliente_ruc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cant_minima', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cant_maxima', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ultima_entrada', models.DateField(auto_now_add=True)),
                ('fecha_ultima_salida', models.DateField(blank=True, null=True)),
                ('detalle_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='administrador.detallecompra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='administrador.item')),
                ('proveedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.proveedor')),
            ],
        ),
    ]
