# Generated by Django 5.1.3 on 2025-04-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cant_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cant_maxima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cant_minima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
