# Generated by Django 5.1.5 on 2025-04-29 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_detallecompra_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='administrador.item'),
        ),
    ]
