# Generated by Django 5.1.5 on 2025-05-02 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(help_text='Debe ser un numero entero mayor a cero', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio'),
        ),
    ]
