# Generated by Django 5.1.3 on 2025-05-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_ingredienteproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nombre'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
