# Generated by Django 5.1.5 on 2025-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_ingredienteproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
