# Generated by Django 5.1.5 on 2025-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_alter_cliente_ruc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nombre'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='producto',
            name='personalizable',
            field=models.BooleanField(default=False),
        ),
    ]
