# Generated by Django 5.1.5 on 2025-05-27 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_alter_item_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario_anulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_anuladas', to=settings.AUTH_USER_MODEL),
        ),
    ]
