# Generated by Django 5.1.5 on 2025-05-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_compra_estado_compra_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='usuario_anulacion',
        ),
    ]
