# Generated by Django 5.1.5 on 2025-06-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_alter_item_options_producto_personalizable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
    ]
