# Generated by Django 5.1.5 on 2025-05-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_alter_item_options_producto_personalizable'),
        ('administrador', '0016_remove_compra_usuario_anulacion'),
    ]

    operations = [
    ]
