# Generated by Django 5.1.5 on 2025-06-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0016_remove_compra_usuario_anulacion'),
        ('administrador', '0017_cliente_user_empleado_user'),
    ]

    operations = [
    ]
